name: trajectory
data_dir: ${oc.env:HOME}/datasets/partnet-mobility

dataset_type: "doors-only"  # "full-dataset"
special_req: "half-half-01"  #"fully-closed", "randomly-open" (no special request)
mask_input_channel: True
randomize_camera: True
randomize_size: False
augmentation: False   # Turn this on with doors-only
seed: 42
n_points: 1200
